# -*- coding: utf-8 -*-
"""English vocabulary list

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W6-t5JkyIbaqwst1ov58QB05VhoOn4oe
"""

import random
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds','https://www.googleapis.com/auth/drive']

#ダウンロードしたjsonファイルをドライブにアップデートした際のパス
json = '/content/drive/MyDrive/english-voca-378420-8764ce1e54f9.json'
credentials = ServiceAccountCredentials.from_json_keyfile_name(json, scope)
gc = gspread.authorize(credentials)

#書き込み先のスプレッドシートキーを追加
SPREADSHEET_KEY = '1RgmtZbTZDbfsx9bQ-eGrGZ1POXknsREP8krgbZ5GPd8'

#creating new sheet
workbook = gc.open_by_key(SPREADSHEET_KEY)
from gspread_dataframe import set_with_dataframe

#The title and the number of row and columns
#workbook.add_worksheet(title='voca4', rows=50, cols=30)

#setting worksheet
worksheet = workbook.worksheet('voca4')

#Skipped Alphabet to create blank columns
import string

s = string.ascii_uppercase
snew=[]

for i in range(0,len(s),2):
  snew.append(s[i])

print(snew)

s = [[1],[2],[3]]

#generate random numbers with skipped alphabet to create blank

for c in snew:
  randomlist = []
  #Generate 10 random numbers between 1 and 2861 in the row(2)
  randomlist = random.sample(range(1, 2862), 10)
  worksheet.update(f'{c}2',[[x] for x in randomlist])

for c in snew:
  randomlist = []
  #Generate 10 random numbers between 1 and 2861 in the row(14)
  randomlist = random.sample(range(1, 2862), 10)
  worksheet.update(f'{c}14',[[x] for x in randomlist])

for c in snew:
  randomlist = []
  #Generate 10 random numbers between 1 and 2861 in the row(26)
  randomlist = random.sample(range(1, 2862), 10)
  worksheet.update(f'{c}26',[[x] for x in randomlist])

#generate random numbers with normal alphabet

for c in s:
  randomlist = []
  #Generate 10 random numbers between 1 and 2861 in the row(2)
  randomlist = random.sample(range(1, 2862), 10)
  worksheet.update(f'{c}2',[[x] for x in randomlist])

for c in s:
  randomlist = []
  #Generate 10 random numbers between 1 and 2861 in the row(14)
  randomlist = random.sample(range(1, 2862), 10)
  worksheet.update(f'{c}14',[[x] for x in randomlist])

for c in s:
  randomlist = []
  #Generate 10 random numbers between 1 and 2861 in the row(26)
  randomlist = random.sample(range(1, 2862), 10)
  worksheet.update(f'{c}26',[[x] for x in randomlist])